// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Reflector.ReflectCommonType(System.String,System.Object,UAlbion.Game.Reflector.ReflectedObject,System.Int32)~UAlbion.Game.Reflector.ReflectedObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Reflector.Reflect(System.String,System.Object,UAlbion.Game.Reflector.ReflectedObject,System.Int32)~UAlbion.Game.Reflector.ReflectedObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Reflector.ReflectCommonType(System.String,System.Object,UAlbion.Game.ReflectedObject,System.Int32)~UAlbion.Game.ReflectedObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Reflector.Reflect(System.String,System.Object,UAlbion.Game.ReflectedObject,System.Int32)~UAlbion.Game.ReflectedObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Assets.AssetLocatorRegistry.LoadAssetInternal(UAlbion.Formats.AssetIds.AssetId)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Don't care about VB", Scope = "member", Target = "~M:UAlbion.Game.Gui.IUiElement.Select(System.Numerics.Vector2,UAlbion.Core.Rectangle,System.Int32,System.Action{System.Int32,System.Object})~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:UAlbion.Game.Gui.UiElement.Select(System.Numerics.Vector2,UAlbion.Core.Rectangle,System.Int32,System.Action{System.Int32,System.Object})~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:UAlbion.Game.Gui.IDialogManager")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:UAlbion.Game.Gui.IFixedSizeUiElement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:UAlbion.Game.Gui.Controls.RepeatedBackground")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:UAlbion.Game.Gui.Controls.DialogFrame")]
