namespace UAlbion.Game.AssetIds
{
    public enum SmallNpcId
    {
        Iskai1 = 0,
        Iskai2 = 1,
        Parrot = 2,
        Pig = 3,
        Flies = 4,
        CatLivestock = 5,
        OldMan = 6,
        Man1 = 7,
        Woman1 = 8,
        Woman2 = 9,
        Woman3 = 10,
        Woman4 = 11,
        Man2 = 12,
        Man3 = 13,
        Man4 = 14,
        Man5 = 15,
        Man6 = 16,
        Ship = 17,
        LargeInsect = 18,
        Toad = 19,
        InsectSwarm1 = 20,
        InsectSwarm2 = 21,
        Krondiir1 = 22,
        Krondiir2 = 23,
        EvilKangaroo = 24,
        PeskyWasp = 25,
        Man7 = 26,
        ScoutShip = 27,
        FloatingHand = 28,
    }
}