namespace UAlbion.Game.Text
{
    public enum Token
    {
        Big,
        Block,
        Centre,
        Class,
        Combatant,
        Damage,
        Fat,
        FatHigh,
        He,
        High,
        Him,
        His,
        Ink,
        Inventory,
        Justify,
        Leader,
        Left,
        Me,
        Name,
        NewLine,
        NormalSize,
        Parameter,
        Price,
        Race,
        Sex,
        Subject,
        Tecf,
        Text,
        Unknown,
        Victim,
        Weapon,
        Word,
        NoWrap
    }
}