// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace UAlbion.Base
{
    //[JsonConverter(typeof(StringEnumConverter))]
    public enum Palette : byte
    {
        Common = 0,
        FirstIslandDay = 1,
        SecondIslandDay = 2,
        JirinaarDay = 3,
        DesertDay = 4,
        StoneyDay = 5,
        IskaiIndoorLight = 6,
        Toronto3D = 7,
        Light2D2 = 8,
        CeltDungeon2D = 9,
        Dark2D = 10,
        Unknown11 = 11,
        Unknown12 = 12,
        Unknown13 = 13,
        Unknown14 = 14,
        GlowyPlantDungeon = 15,
        Stoney2D = 16,
        Unknown17 = 17,
        Unknown18 = 18,
        Inventory = 19,
        IskaiIndoorDark = 20,
        Unknown21 = 21,
        Unknown22 = 22,
        PlainsCombat = 23,
        DungeonCombat = 24,
        BelovenoDay = 25,
        Toronto2D = 26,
        DesertCombat = 27,
        Celtic2D = 28,
        Unknown29 = 29,
        Unknown30 = 30,
        Unknown31 = 31,
        WoodDungeonCombat = 32,
        BarrelDungeonCombat = 33,
        TableDungeonCombat = 34,
        FireDungeonCombat = 35,
        PlantDungeonCombat = 36,
        CaveCombat = 37,
        TorontoCombat = 38,
        LivingWallsCombat = 39,
        ForestCombat = 40,
        TownNightCombat = 41,
        TownCombat = 42,
        PlainsCombat2 = 43,
        PlainsCombat3 = 44,
        DjiKantos2D = 45,
        Unknown46 = 46,
        OutdoorsNight = 47,
        DesertNight = 48,
        BelovenoNight = 49,
        VeryBlue = 50,
        BelovenoDusk = 51,
        DesertNightCombat = 52,
        ForestNightCombat = 53,
        ForestNightCombat2 = 54,
        JirinaarNight = 55,
        TileSet10 = 56,
    }
}
