// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace UAlbion.Base
{
    //[JsonConverter(typeof(StringEnumConverter))]
    public enum Picture : byte
    {
        SmallWizard = 1,
        HarbourTown = 2,
        ScoutShip = 3,
        BildDesPlanetenText = 4,
        LabyrinthMap = 5,
        HutByAWaterfall = 6,
        MagiciansWithSeed = 7,
        CelticVillage = 8,
        CelticMelee = 9,
        CelticIskaiStandoff = 10,
        OpenChest = 11,
        OpenChestWithGold = 12,
        ClosedChest = 13,
        LootPile = 14,
        TorontoWithVines = 15,
        TorontoWithVinesAndParty = 16,
        EndgameScreenshot = 17,
        WoodenDoor = 18,
        MenuBackground = 19,
        MenuBackground2 = 20,
        MenuBackground3 = 21,
        MenuBackground4 = 22,
        MenuBackground5 = 23,
        MenuBackground6 = 24,
        MenuBackground7 = 25,
        MenuBackground8 = 26,
        MenuBackground9 = 27,
        ColouredPlateMap = 28,
        SecretCaveMap = 29,
        Boop = 30,
        PartyResting = 31,
        CelticVillageScreenshot = 32,
        DungeonScreenshot = 33,
        CelticIndoorsScreenshot = 34,
        HouseScreenshot = 35,
        DjiKantosScreenshot = 36,
        RiversideScreenshot = 37,
        HarbourScreenshot = 38,
        DesertScreenshot = 39,
        EndgameScreenshot2 = 40,
        PressurePlateScreenshot = 41,
        KengetScreenshot = 42,
        DungeonScreenshot2 = 43,
        CombatScreenshot = 44,
        CombatScreenshot2 = 45,
        TestMap = 99,
        StatusBar = 100,
    }
}
