// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace UAlbion.Base;

#pragma warning disable CA1027
public enum Picture : byte
{
    SmallWizard = 1,
    HarbourTown = 2,
    ScoutShip = 3,
    BildDesPlanetenText = 4,
    LabyrinthMap = 5,
    HutByAWaterfall = 6,
    MagiciansWithSeed = 7,
    CelticVillage = 8,
    CelticMelee = 9,
    CelticIskaiStandoff = 10,
    OpenChest = 11,
    OpenChestWithGold = 12,
    ClosedChest = 13,
    LootPile = 14,
    TorontoWithVines = 15,
    TorontoWithVinesAndParty = 16,
    EndgameScreenshot = 17,
    WoodenDoor = 18,
    // MenuBackground = 19,
    MenuBackground1 = 20,
    MenuBackground2 = 21,
    MenuBackground3 = 22,
    MenuBackground4 = 23,
    MenuBackground5 = 24,
    MenuBackground6 = 25,
    MenuBackground7 = 26,
    MenuBackground8 = 27,
    ColouredPlateMap = 28,
    SecretCaveMap = 29,
    Boop = 30,
    PartyResting = 31,
    CelticVillageScreenshot = 32,
    DungeonScreenshot = 33,
    CelticIndoorsScreenshot = 34,
    HouseScreenshot = 35,
    DjiKantosScreenshot = 36,
    RiversideScreenshot = 37,
    HarbourScreenshot = 38,
    DesertScreenshot = 39,
    EndgameScreenshot2 = 40,
    PressurePlateScreenshot = 41,
    KengetScreenshot = 42,
    DungeonScreenshot2 = 43,
    CombatScreenshot = 44,
    CombatScreenshot2 = 45,
    // TestMap = 99,
    // StatusBar = 100,
}