// Note: This file was automatically generated using Tools/GenerateEnums.
// No changes should be made to this file by hand. Instead, the relevant json 
// files should be modified and then GenerateEnums should be used to regenerate
// the various ID enums.

namespace UAlbion.Formats.AssetIds
{
    public enum CoreSpriteId
    {
        Cursor = 0,
        Cursor3dUp = 1,
        Cursor3dDown = 2,
        Cursor3dLeft = 3,
        Cursor3dRight = 4,
        Cursor3dTurnLeft90 = 5,
        Cursor3dTurnRight90 = 6,
        Cursor3dTurnLeft180 = 7,
        Cursor3dTurnRight180 = 8,
        Cursor2dUp = 9,
        Cursor2dDown = 10,
        Cursor2dLeft = 11,
        Cursor2dRight = 12,
        Cursor2dUpLeft = 13,
        Cursor2dUpRight = 14,
        Cursor2dDownRight = 15,
        Cursor2dDownLeft = 16,
        CursorSelected = 17,
        CursorCdLoad = 18,
        CursorWait = 19,
        CursorMouseClick = 20,
        CursorSmall = 21,
        CursorCrossSelected = 22,
        CursorCrossUnselected = 23,
        CursorMemoryLoad = 24,
        CursorUpLeft = 25,
        CursorUpRight = 26,
        UiBackground = 27,
        UiBackgroundStriped = 28,
        UiBackgroundLines = 29,
        UiWindowTopLeft = 30,
        UiWindowTopRight = 31,
        UiWindowBottomLeft = 32,
        UiWindowBottomRight = 33,
        UiExitButton1 = 34,
        UiExitButton2 = 35,
        UiExitButton3 = 36,
        UiOffensiveValue = 37,
        UiDefensiveValue = 38,
        UiGold = 39,
        UiFood = 40,
        UiNa = 41,
        UiBroken = 42,
        UiSpellAdvance = 43,
        CombatMove = 44,
        CombatAttackMelee = 45,
        CombatAttackRange = 46,
        CombatRetreat = 47,
        CombatMagic = 48,
        CombatMagicItem = 49,
        MonsterEyeOff = 50,
        MonsterEyeOn = 51,
        Clock = 52,
        ClockNum0 = 53,
        ClockNum1 = 54,
        ClockNum2 = 55,
        ClockNum3 = 56,
        ClockNum4 = 57,
        ClockNum5 = 58,
        ClockNum6 = 59,
        ClockNum7 = 60,
        ClockNum8 = 61,
        ClockNum9 = 62,
        CompassDe = 63,
        CompassEn = 64,
        CompassFr = 65,
        CompassDot0 = 66,
        CompassDot1 = 67,
        CompassDot2 = 68,
        CompassDot3 = 69,
        CompassDot4 = 70,
        CompassDot5 = 71,
        CompassDot6 = 72,
        CompassDot7 = 73,
        Select = 74,
        Lock = 75,
        Producer = 76,
        CharEffect1 = 77,
        CharEffect2 = 78,
        CharEffect3 = 79,
        ArrowTurnLeft90 = 80,
        ArrowTurnRight90 = 81,
        ArrowTurnLeft180 = 82,
        ArrowTurnRight180 = 83,
        ArrowLookUp = 84,
        ArrowLookDown = 85,
    }
}