// Note: This file was automatically generated using Tools/GenerateEnums.
// No changes should be made to this file by hand. Instead, the relevant json
// files should be modified and then GenerateEnums should be used to regenerate
// the various ID enums.

// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace UAlbion.Formats.AssetIds
{
    public enum MonsterGraphicsId : byte
    {
        FloatingHand = 0,
        Unknown1 = 1,
        Unknown2 = 2,
        Unknown3 = 3,
        Unknown4 = 4,
        Unknown5 = 5,
        EvilKangaroo = 6,
        EvilKangaroo2 = 7,
        Unknown8 = 8,
        Krondiir = 9,
        Krondiir2 = 10,
        Unknown11 = 11,
        PeskyWasp = 12,
        PeskyWasp2 = 13,
        PeskyWasp3 = 14,
        Raptor = 15,
        Raptor2 = 16,
        Raptor3 = 17,
        SpiderMajigger = 18,
        SpiderMajigger2 = 19,
        SpiderMajigger3 = 20,
        WormThingy = 21,
        WormThingy2 = 22,
        WormThingy3 = 23,
        Unknown24 = 24,
        Unknown25 = 25,
        Unknown26 = 26,
        Robot = 27,
        Unknown28 = 28,
        Unknown29 = 29,
        Iskai = 30,
        Iskai2 = 31,
        Iskai3 = 32,
        Celt = 33,
        Celt2 = 34,
        Celt3 = 35,
        Wizard = 36,
        Wizard2 = 37,
        Wizard3 = 38,
        Celt4 = 39,
        Celt5 = 40,
        Celt6 = 41,
        Security = 42,
        Security2 = 43,
        Unknown44 = 44,
        Ned = 45,
        Ned2 = 46,
        Unknown47 = 47,
        Demon = 48,
        Demon2 = 49,
        Demon3 = 50,
        AngryCloud = 51,
        AngryCloud2 = 52,
        AngryCloud3 = 53,
        Zombie = 54,
        Zombie2 = 55,
        Zombie3 = 56,
        Priest = 57,
        WobblyThing = 58,
        Cpu = 59,
    }
}
